### ISSUE TITLE
Reformat output columns

### ISSUE THREAD

**Issue by M-R-JONES** [precisiontox/ptox-metadata-manager#94] opened 2023-08-02 14:37 UTC
Hi @terazus,

Regarding outputs of experiment creation tool, can we standardise the headings and reorder:

![image](https://github.com/precisiontox/ptox-metadata-manager/assets/6332174/e8558f5d-3357-4708-9967-72929f58f3df)

Below, number refers to preferred order and right side of "->" is preferred name:

- [x] [add] ptox_hashid
- [x] compound_hash
- [x] sampleID_label -> sampleid_label 
- [x] Shipment_identifier -> shipment_identifier
- [x] operator
- [x] quantity_dead_during_exposure
- [x] amount_replaced_before_collection
- [x] collection_order
- [x] box_id
- [x] box_row
- [x] box_column

EDIT (Terazus):
- [x] PrecisionTox_short_identifier -> precisiontox_short_identifier

I think the following could be dropped @RJMW, do you agree?
1. "exposure_route" - I would suggest that we can exclude this in the case of PTox, as we know the route used for each test system.
2. "Mass_including_tube_(mg)" - partners are now not weighing each sample (though, ideally would if it did not cause collection delays and balances are available that are sensitive enough).
3. "Mass_excluding_tube_(mg)" - partners are now not weighing each sample.

**Comment by terazus** [comment] 2023-08-03 10:09
During our last meeting:
- ptox_hasid was requested to be dropped as it is a duplicate of either sampleid_label or precisionTox_short_identifier.
- exposure route and mass fields were requested to be added
Thus I am not very keen on reworking them fATM.

**Closed** 2023-08-03 13:24 UTC
